desktop: 
  background_image_file: assets/bg-green.jpg

printer:
  default_printer: ricoh_c3010
 
  with_ppd:
    ricoh_c3010:
      display_name: P11567 - Ricoh C3010
      protocol: socket
      ip: 10.1.1.30
      ppd_file: assets/Ricoh-IM_C3010-PDF-Ricoh.ppd
      settings:
        page_size: A4
        color_mode: rgb
        duplex: none
        orientation: portrait


