targets:
  - name: Broager
    description: Build image for Broager locations
    groups:
      - broager
    image_name: broager

  - name: Nordborg
    description: Build image for Nordborg and Borgerservice overlays
    groups:
      - nordborg
      - borgerservice
    image_name: nordborg
