all:
  children:
    printer_x:
      hosts:
        pc01:
        pc02:

    printer_y:
      hosts:
        pc03:
        pc04:

    wallpaper_1:
      hosts:
        pc01:
        pc03:
        pc05:

    wallpaper_2:
      hosts:
        pc02:
        pc04:
        pc06:

    wifi_office:
      hosts:
        pc01:
        pc02:
        pc03:

    wifi_guest:
      hosts:
        pc04:
        pc05:
        pc06:
