targets:
  - name: Nordborg
    description: Build image for Nordborg
    groups:
      - borgerpc-basis
      - nordborg
    image_name: nordborg
    
  - name: Broager
    description: Build image for Broager
    groups:
      - borgerpc-basis
      - broager
    image_name: broager
